import '../models/daily_entry.dart';
import '../models/task.dart';
import '../models/task_entry.dart';
import '../models/task_type.dart';

class TaskMappingService {
  // Mapping from old hardcoded task types to new dynamic task type names
  static const Map<String, String> _legacyToNewTaskTypeMapping = {
    'readingBook': 'reading_book',
    'stretch': 'stretch_exercise', 
    'meditation': 'meditation',
    'readingDocs': 'reading_docs',
    'learningTech': 'learning_tech',
    'walking': 'walking',
    'avoidHabit': 'habit',
    'avoidSweets': 'habit', 
    'workDone': 'habit',
    'movieSeries': 'entertainment',
  };

  // Mapping from new dynamic task type names to old hardcoded task types
  static const Map<String, String> _newToLegacyTaskTypeMapping = {
    'reading_book': 'readingBook',
    'stretch_exercise': 'stretch',
    'meditation': 'meditation', 
    'reading_docs': 'readingDocs',
    'learning_tech': 'learningTech',
    'walking': 'walking',
    'habit': 'avoidHabit', // Default mapping for habit type
    'entertainment': 'movieSeries',
  };

  // Convert DailyEntry hardcoded fields to TaskEntry data
  static List<TaskEntry> convertDailyEntryToTaskEntries({
    required DailyEntry dailyEntry,
    required List<Task> userTasks,
    required List<TaskType> taskTypes,
  }) {
    final List<TaskEntry> taskEntries = [];
    final now = DateTime.now();

    for (final task in userTasks) {
      final taskType = taskTypes.firstWhere(
        (type) => type.id == task.taskTypeId,
        orElse: () => TaskType(
          id: '',
          name: 'unknown',
          description: '',
          schemaDefinition: {},
          isActive: true,
          createdAt: now,
          updatedAt: now,
        ),
      );

      Map<String, dynamic> data = {};
      bool completed = false;

      // Map based on task type and task name
      switch (taskType.name) {
        case 'reading_book':
          completed = dailyEntry.readingBookCompleted;
          data = {
            'pages': dailyEntry.readingBookPages,
            'time': dailyEntry.readingBookTime,
          };
          break;

        case 'stretch_exercise':
          completed = dailyEntry.stretchCompleted;
          data = {
            'type': dailyEntry.stretchType,
            'minutes': dailyEntry.stretchMinutes,
          };
          break;

        case 'meditation':
          completed = dailyEntry.meditationCompleted;
          data = {
            'minutes': dailyEntry.meditationMinutes,
          };
          break;

        case 'reading_docs':
          completed = dailyEntry.readingDocsCompleted;
          data = {
            'pages': dailyEntry.readingDocsPages,
            'time': dailyEntry.readingDocsTime,
          };
          break;

        case 'learning_tech':
          completed = dailyEntry.learningTechCompleted;
          data = {
            'name': dailyEntry.learningTechName,
            'time': dailyEntry.learningTechTime,
          };
          break;

        case 'walking':
          completed = dailyEntry.walkingCompleted;
          data = {
            'steps': dailyEntry.walkingSteps,
            'time': dailyEntry.walkingTime,
          };
          break;

        case 'habit':
          // Map specific habit tasks based on task name
          if (task.name == 'Avoid Bad Habit') {
            completed = dailyEntry.avoidHabitValue;
            data = {
              'label': dailyEntry.avoidHabitLabel,
            };
          } else if (task.name == 'Avoid Sweets') {
            completed = dailyEntry.avoidSweetsValue;
          } else if (task.name == 'Work Done Today') {
            completed = dailyEntry.workDoneValue;
          }
          break;

        case 'entertainment':
          completed = dailyEntry.movieSeriesCompleted;
          data = {
            'name': dailyEntry.movieSeriesName,
            'duration': dailyEntry.movieSeriesDuration,
          };
          break;
      }

      // Remove null values from data
      data.removeWhere((key, value) => value == null);

      taskEntries.add(TaskEntry(
        id: '', // Will be generated by database
        dailyEntryId: dailyEntry.id,
        taskId: task.id,
        data: data,
        completed: completed,
        createdAt: now,
        updatedAt: now,
      ));
    }

    return taskEntries;
  }

  // Convert TaskEntry data back to DailyEntry fields (for backward compatibility)
  static DailyEntry convertTaskEntriesToDailyEntry({
    required DailyEntry baseDailyEntry,
    required List<TaskEntry> taskEntries,
    required List<Task> userTasks,
    required List<TaskType> taskTypes,
  }) {
    // Start with the base daily entry
    var updatedEntry = baseDailyEntry;

    for (final taskEntry in taskEntries) {
      final task = userTasks.firstWhere(
        (t) => t.id == taskEntry.taskId,
        orElse: () => Task(
          id: '',
          userId: '',
          taskTypeId: '',
          name: '',
          createdAt: DateTime.now(),
          updatedAt: DateTime.now(),
        ),
      );

      final taskType = taskTypes.firstWhere(
        (type) => type.id == task.taskTypeId,
        orElse: () => TaskType(
          id: '',
          name: 'unknown',
          description: '',
          schemaDefinition: {},
          isActive: true,
          createdAt: DateTime.now(),
          updatedAt: DateTime.now(),
        ),
      );

      // Map back to DailyEntry fields based on task type
      switch (taskType.name) {
        case 'reading_book':
          updatedEntry = updatedEntry.copyWith(
            readingBookCompleted: taskEntry.completed,
            readingBookPages: taskEntry.getIntValue('pages'),
            readingBookTime: taskEntry.getIntValue('time'),
          );
          break;

        case 'stretch_exercise':
          updatedEntry = updatedEntry.copyWith(
            stretchCompleted: taskEntry.completed,
            stretchType: taskEntry.getStringValue('type'),
            stretchMinutes: taskEntry.getIntValue('minutes'),
          );
          break;

        case 'meditation':
          updatedEntry = updatedEntry.copyWith(
            meditationCompleted: taskEntry.completed,
            meditationMinutes: taskEntry.getIntValue('minutes'),
          );
          break;

        case 'reading_docs':
          updatedEntry = updatedEntry.copyWith(
            readingDocsCompleted: taskEntry.completed,
            readingDocsPages: taskEntry.getIntValue('pages'),
            readingDocsTime: taskEntry.getIntValue('time'),
          );
          break;

        case 'learning_tech':
          updatedEntry = updatedEntry.copyWith(
            learningTechCompleted: taskEntry.completed,
            learningTechName: taskEntry.getStringValue('name'),
            learningTechTime: taskEntry.getIntValue('time'),
          );
          break;

        case 'walking':
          updatedEntry = updatedEntry.copyWith(
            walkingCompleted: taskEntry.completed,
            walkingSteps: taskEntry.getIntValue('steps'),
            walkingTime: taskEntry.getIntValue('time'),
          );
          break;

        case 'habit':
          // Map specific habit tasks based on task name
          if (task.name == 'Avoid Bad Habit') {
            updatedEntry = updatedEntry.copyWith(
              avoidHabitValue: taskEntry.completed,
              avoidHabitLabel: taskEntry.getStringValue('label'),
            );
          } else if (task.name == 'Avoid Sweets') {
            updatedEntry = updatedEntry.copyWith(
              avoidSweetsValue: taskEntry.completed,
            );
          } else if (task.name == 'Work Done Today') {
            updatedEntry = updatedEntry.copyWith(
              workDoneValue: taskEntry.completed,
            );
          }
          break;

        case 'entertainment':
          updatedEntry = updatedEntry.copyWith(
            movieSeriesCompleted: taskEntry.completed,
            movieSeriesName: taskEntry.getStringValue('name'),
            movieSeriesDuration: taskEntry.getIntValue('duration'),
          );
          break;
      }
    }

    return updatedEntry;
  }

  // Get legacy task type from new task type name
  static String? getLegacyTaskType(String newTaskTypeName) {
    return _newToLegacyTaskTypeMapping[newTaskTypeName];
  }

  // Get new task type name from legacy task type
  static String? getNewTaskTypeName(String legacyTaskType) {
    return _legacyToNewTaskTypeMapping[legacyTaskType];
  }

  // Check if a task type is a habit-based task
  static bool isHabitTask(String taskTypeName) {
    return taskTypeName == 'habit';
  }

  // Get default task names for habit tasks
  static List<String> getDefaultHabitTaskNames() {
    return ['Avoid Bad Habit', 'Avoid Sweets', 'Work Done Today'];
  }
}