class DailyEntry {
  final String id;
  final String userId;
  final DateTime date;
  final String? notes;
  final int timezoneOffset;
  final DateTime createdAt;
  final DateTime updatedAt;
  final DateTime? clientUpdatedAt;
  final DateTime? deletedAt;
  final int schemaVersion;

  const DailyEntry({
    required this.id,
    required this.userId,
    required this.date,
    this.notes,
    required this.timezoneOffset,
    required this.createdAt,
    required this.updatedAt,
    this.clientUpdatedAt,
    this.deletedAt,
    this.schemaVersion = 2,
  });

  factory DailyEntry.fromJson(Map<String, dynamic> json) {
    return DailyEntry(
      id: json['id'],
      userId: json['user_id'],
      date: DateTime.parse(json['date']),
      notes: json['notes'],
      timezoneOffset: json['timezone_offset'] ?? 0,
      createdAt: DateTime.parse(json['created_at']),
      updatedAt: DateTime.parse(json['updated_at']),
      clientUpdatedAt: json['client_updated_at'] != null ? DateTime.parse(json['client_updated_at']) : null,
      deletedAt: json['deleted_at'] != null ? DateTime.parse(json['deleted_at']) : null,
      schemaVersion: json['schema_version'] ?? 2,
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'user_id': userId,
      'date': date.toIso8601String().split('T')[0],
      if (notes != null) 'notes': notes,
      'timezone_offset': timezoneOffset,
      'created_at': createdAt.toIso8601String(),
      'updated_at': updatedAt.toIso8601String(),
      if (clientUpdatedAt != null) 'client_updated_at': clientUpdatedAt!.toIso8601String(),
      if (deletedAt != null) 'deleted_at': deletedAt!.toIso8601String(),
      'schema_version': schemaVersion,
    };
  }

  DailyEntry copyWith({
    String? id,
    String? userId,
    DateTime? date,
    String? notes,
    int? timezoneOffset,
    DateTime? createdAt,
    DateTime? updatedAt,
    DateTime? clientUpdatedAt,
    DateTime? deletedAt,
    int? schemaVersion,
  }) {
    return DailyEntry(
      id: id ?? this.id,
      userId: userId ?? this.userId,
      date: date ?? this.date,
      notes: notes ?? this.notes,
      timezoneOffset: timezoneOffset ?? this.timezoneOffset,
      createdAt: createdAt ?? this.createdAt,
      updatedAt: updatedAt ?? this.updatedAt,
      clientUpdatedAt: clientUpdatedAt ?? this.clientUpdatedAt,
      deletedAt: deletedAt ?? this.deletedAt,
      schemaVersion: schemaVersion ?? this.schemaVersion,
    );
  }

  factory DailyEntry.empty({required DateTime date, int? timezoneOffset}) {
    final now = DateTime.now();
    return DailyEntry(
      id: '', // Will be generated by database
      userId: '', // Will be set by trigger
      date: date,
      timezoneOffset: timezoneOffset ?? now.timeZoneOffset.inMinutes,
      createdAt: now,
      updatedAt: now,
    );
  }
}